### ISSUE TITLE
Creación de modulo coffee

### ISSUE THREAD

**Issue by jjhoncv** [frontend-labs/flux#10]
Creación de un archivo README.md en la siguiente ruta:
flux/frontend/miproyecto/coffee/scripts/modules/

Explicando la creación de un modulo en coffee, debe ser descriptivo, indicando los pro y los contra de cada sección, y como debe comportarse respecto a los demás módulos.

**Comment by jansanchez** [comment]
Genial! buen aporte Jhonathan!

**Comment by jansanchez** [comment]
Se Realizo el merge con exito
