### ISSUE TITLE
Las Tareas Sprites y Mocha necesitan ser actualizadas

### ISSUE THREAD

**Issue by carloshs92** [frontend-labs/flux#36]
Actualmente al ejecutar gulp sprites o gulp mocha por la terminal estas generan errores al buscar una función que no existe

**Comment by jansanchez** [comment]
:+1:

**Comment by carloshs92** [comment]
En el pull request #37 se cierra este issue.

closes #36

**Comment by carloshs92** [comment]
En el pull request #37 se cierra este issue.
