### ISSUE TITLE
contextify don't work with Node 4.x

### ISSUE THREAD

**Issue by Edux87** [frontend-labs/flux#56]
Cuando instalo contextify usando node 4.1.0, se obtiene un ERR, 
`npm ERR! contextify@0.1.14 install: node-gyp rebuild`
https://github.com/brianmcd/contextify/issues/180#issuecomment-142148574

**Comment by Edux87** [comment]
Solucionado con instalar previamente, 
`npm install -g node-gyp`

**Comment by carloshs92** [comment]
:+1:
