### ISSUE TITLE
Actualizar path para la dependencia de jquery de flux

### ISSUE THREAD

**Issue by pakgva** [frontend-labs/flux#9]
En el partial de footer_scripts de la carpeta jadeflux el path se encuentra desactualizado para la dependencia de jquery 1.11 como se muestra a continuación en el siguiente enlace

[Linea 1 - jadeflux/_partials/footer_scripts.jade](https://github.com/frontend-labs/flux/blob/master/frontend/miproyecto/jadeflux/_partials/footer_scripts.jade#L1)

Se debe actualizar con la siguiente sintaxis

```jade
script(src="#{page.static_url}js/dist/libs/jquery/jquery.min.js#{page.version}", type="text/javascript")
```

**Comment by andru255** [comment]
Porfa @jansanchez  actualizar el repo con el cambio indicado
